save : False
dt: 0.01
samples: 30
alpha : 0.785 # pi/4
cuda: True # server False

monitoring: True

sbatch: 32
tbatch: 32
lr: 0.0001
bias: False
nodes: 3
no_loops: True
sob:
  - 1.0
  - 1.0
  - 1.0

layer: GAT
size: 128
e_size: 16

train_break: -1
test_break: -1

epochs: 10000
sim_type: dat_fig

max_sim_time: 259200 # 3 days

wandb: True